apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster

# the mirrors config works good to me.
# please changed it to your own mirrors
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."hub.docker.com"]
      endpoint = [
        "https://docker.mirrors.ustc.edu.cn"
      ]
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."gcr.io"]
      endpoint = [
        "https://gcr.mirrors.ustc.edu.cn"
      ]
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."public.ecr.aws"]
      endpoint = [
        "https://public-ecr-mirror.mirrors.ustc.edu.cn"
      ]
nodes:
  - role: control-plane
    # https://hub.docker.com/r/kindest/node/tags
    image: kindest/node:v1.27.11
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
      - containerPort: 31021
        hostPort: 15021
        protocol: TCP
      - containerPort: 31443
        hostPort: 15443
        protocol: TCP
      - containerPort: 31012
        hostPort: 15012
        protocol: TCP
      - containerPort: 31017
        hostPort: 15017
        protocol: TCP
      # # TCP port for application use such as:
      # # https://istio.io/latest/docs/tasks/traffic-management/tcp-traffic-shifting/
      # - containerPort: 31400
      #   hostPort: 31400
      #   protocol: TCP
  - role: worker
    image: kindest/node:v1.27.11
  # - role: worker
  #   kubeadmConfigPatches:
  #   - |
  #     kind: JoinConfiguration
  #     nodeRegistration:
  #       kubeletExtraArgs:
  #         node-labels: "cluster_components=true"
  #       taints:
  #       - effect: "NoSchedule"
  #         key: "cluster_components"
  #         value: "true"

# Network plugin configuration can follow cilium documentation.
# https://docs.cilium.io/en/stable/installation/kind/
networking:
  disableDefaultCNI: false

# https://kind.sigs.k8s.io/docs/user/configuration/#feature-gates
featureGates:
  PodSecurity: true
# "PodSecurityPolicy": true
# runtimeConfig:
#   "api/alpha": "false"
#   "api/beta": "true"
